# -*- coding: utf-8 -*-
"""PhishingEmailDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1njMRiIt3wqkk4ZRVR7xVtA8p36qFAgGJ
"""

# Cell 1 — connect Colab to your Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Cell 2 — load the dataset
import pandas as pd

# adjust this to match wherever you placed the file in your Drive
csv_path = '/content/drive/MyDrive/Colab Notebooks/phishing_email.csv'
df = pd.read_csv(csv_path)

df.head()

# Cell 3 — basic shape and column check
print("Shape (rows, columns):", df.shape)
print("\nColumn names:", df.columns.tolist())
df.info()

# Cell 4 — missing values and duplicates
print("Missing values per column:\n", df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())

# Cell 5 — class balance (this dataset is usually labeled 0 = legitimate, 1 = phishing)
df['label'].value_counts()

# Cell 6 — peek at one example of each class
print("Example phishing email:\n", df[df['label'] == 1].iloc[0])
print("\nExample legitimate email:\n", df[df['label'] == 0].iloc[0])

# Cell 7 — remove duplicate emails
df = df.drop_duplicates()
print("New shape after removing duplicates:", df.shape)

# Cell 8 — visualize class distribution
import matplotlib.pyplot as plt

df['label'].value_counts().plot(kind='bar', color=['#4C72B0', '#DD8452'])
plt.title('Email Class Distribution')
plt.xlabel('Label (0 = Legitimate, 1 = Phishing)')
plt.ylabel('Number of Emails')
plt.xticks(rotation=0)
plt.show()

# Cell 9 — engineer extra features from the raw text
#import re

#df['text_length'] = df['text_combined'].apply(len)
#df['url_count'] = df['text_combined'].apply(lambda t: len(re.findall(r'http\S+|www\.\S+', str(t))))
#df['exclaim_count'] = df['text_combined'].apply(lambda t: str(t).count('!'))

# compare the averages between phishing and legitimate emails
#df[['text_length', 'url_count', 'exclaim_count', 'label']].groupby('label').mean()

#----------------------------------------------------------------------------------
# Cell 9 (revised) — swap the dead feature for one that actually varies
#df['text_length'] = df['text_combined'].apply(len)
#df['url_count'] = df['text_combined'].apply(lambda t: len(re.findall(r'http\S+|www\.\S+', str(t))))
#df['digit_count'] = df['text_combined'].apply(lambda t: sum(c.isdigit() for c in str(t)))

#df[['text_length', 'url_count', 'digit_count', 'label']].groupby('label').mean()
#----------------------------------------------------------------------------------

# Cell 9 — engineer extra features from the raw text
import re

df['text_length'] = df['text_combined'].apply(len)
df['url_count'] = df['text_combined'].apply(lambda t: len(re.findall(r'http\S+|www\.\S+', str(t))))
df['digit_count'] = df['text_combined'].apply(lambda t: sum(c.isdigit() for c in str(t)))

df[['text_length', 'url_count', 'digit_count', 'label']].groupby('label').mean()

# Cell 10 — visualize email length by class
#plt.figure(figsize=(8, 5))
#df[df['label'] == 0]['text_length'].plot(kind='hist', bins=50, alpha=0.6, label='Legitimate')
#df[df['label'] == 1]['text_length'].plot(kind='hist', bins=50, alpha=0.6, label='Phishing')
#plt.xlim(0, 5000)
#plt.title('Email Length Distribution by Class')
#plt.xlabel('Character count')
#plt.ylabel('Number of Emails')
#plt.legend()
#plt.show()

#----------------------------------------------------------------------------------

# Cell 10 — visualize email length by class
plt.figure(figsize=(8, 5))
bins = range(0, 5000, 100)
df[(df['label'] == 0) & (df['text_length'] < 5000)]['text_length'].plot(kind='hist', bins=bins, alpha=0.6, label='Legitimate')
df[(df['label'] == 1) & (df['text_length'] < 5000)]['text_length'].plot(kind='hist', bins=bins, alpha=0.6, label='Phishing')
plt.title('Email Length Distribution by Class')
plt.xlabel('Character count')
plt.ylabel('Number of Emails')
plt.legend()
plt.show()

# Cell 11 — clean and normalize the email text
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'<.*?>', ' ', text)              # strip HTML tags
    text = re.sub(r'http\S+|www\.\S+', ' ', text)    # strip URLs
    text = re.sub(r'[^a-z\s]', ' ', text)            # keep only letters
    text = re.sub(r'\s+', ' ', text).strip()         # collapse extra spaces
    return text

df['clean_text'] = df['text_combined'].apply(clean_text)
df[['text_combined', 'clean_text']].head()

# New cell — catch and remove duplicates that only appear after cleaning
post_clean_dupes = df['clean_text'].duplicated().sum()
print("Duplicate rows after cleaning:", post_clean_dupes)

df = df.drop_duplicates(subset='clean_text').reset_index(drop=True)
print("Shape after removing post-cleaning duplicates:", df.shape)

# Cell 12 — TF-IDF vectorization
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000, min_df=5, max_df=0.9)
X_tfidf = tfidf.fit_transform(df['clean_text'])
print("TF-IDF matrix shape:", X_tfidf.shape)

# Cell 13 — combine TF-IDF with the handcrafted features

from scipy.sparse import hstack, csr_matrix

extra_features = csr_matrix(df[['text_length', 'url_count', 'digit_count']].values)
X = hstack([X_tfidf, extra_features])
y = df['label']
print("Final feature matrix shape:", X.shape)

# Cell 14 — train/test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print("Training set size:", X_train.shape)
print("Testing set size:", X_test.shape)

# Cell 15 — initialize and train the Random Forest
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
rf_model.fit(X_train, y_train)
print("Model trained on", X_train.shape[0], "emails.")

# Cell 16 — quick sanity check (just to confirm it learned something — not the real evaluation)
print("Quick accuracy check:", rf_model.score(X_test, y_test))

# Cell 17 — check for duplicates that only appear after cleaning
print("Duplicate rows after cleaning:", df['clean_text'].duplicated().sum())

# Cell 18 — full evaluation: precision, recall, F1, ROC-AUC
from sklearn.metrics import classification_report, accuracy_score, roc_auc_score

y_pred = rf_model.predict(X_test)
y_prob = rf_model.predict_proba(X_test)[:, 1]

print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))
print()
print(classification_report(y_test, y_pred,
      target_names=['Legitimate (0)', 'Phishing (1)'], digits=4))

# Cell 19 — confusion matrix
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_test, y_pred)
print(cm)   # layout: [[TN, FP], [FN, TP]]

disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Legitimate', 'Phishing'])
disp.plot(cmap='Blues', values_format='d')
plt.title('Confusion Matrix - Random Forest')
plt.show()

# Cell 20 — top 20 most important features
import numpy as np

feature_names = list(tfidf.get_feature_names_out()) + ['text_length', 'url_count', 'digit_count']
importances = rf_model.feature_importances_
top_idx = np.argsort(importances)[::-1][:20]

for rank, i in enumerate(top_idx, start=1):
    print(f"{rank:2d}. {feature_names[i]:<20} {importances[i]:.4f}")

print("\nShare of importance from the 3 handcrafted features:", importances[-3:].sum())

plt.figure(figsize=(8, 6))
plt.barh([feature_names[i] for i in top_idx][::-1], importances[top_idx][::-1])
plt.title('Top 20 Feature Importances - Random Forest')
plt.xlabel('Importance')
plt.tight_layout()
plt.show()